title: The Crafty Machinist
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

color_scheme: TCM

url: https://ZipZapCraftShack.github.io/TCM_JTD

aux_links:
  Store: https://thecraftymachinist.com/

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/3 Flute.png"

# Set a path/url to a favicon that will be displayed by the browser
#favicon_ico: "/assets/images/favicon.ico"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'
  
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Define Jekyll collections
collections_dir: docs

collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  ChoosingACuttingTool:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    ChoosingACuttingTool:
      # Give the collection a name
      name: Choosing A Cutting Tool
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false

      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: false  # note: this option is new in v0.4

      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

callouts:
  warning:
    title: Warning
    color: red
  grey-lt:
    title: Note
    color: grey-lt
  yellow:
    title: Note
    color: yellow
  green:
    title: Note
    color: green