# =============================================================================
# The Crafty Machinist - Jekyll Configuration
# =============================================================================
# Theme: Just the Docs
# Documentation: https://just-the-docs.github.io/just-the-docs/
# =============================================================================

# -----------------------------------------------------------------------------
# Site Metadata
# -----------------------------------------------------------------------------
title: The Crafty Machinist
description: Manufacturing education for K-12 students, hobbyists, and small businesses - from 3D printing to CNC machining
author: The Crafty Machinist
email: info@thecraftymachinist.com
lang: en-US
timezone: America/New_York

# -----------------------------------------------------------------------------
# URLs and Deployment
# -----------------------------------------------------------------------------
url: https://ZipZapCraftShack.github.io
baseurl: /TCM_JTD                      # Repository name for GitHub Pages
repository: ZipZapCraftShack/TCM_JTD   # GitHub username/repo-name

# -----------------------------------------------------------------------------
# Build Settings
# -----------------------------------------------------------------------------
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs  # For GitHub Pages
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - README.md
  - LICENSE

# -----------------------------------------------------------------------------
# Directory Structure
# -----------------------------------------------------------------------------
source: .
destination: _site
collections_dir: .

# -----------------------------------------------------------------------------
# Theme Configuration
# -----------------------------------------------------------------------------
# Logo and Branding
# logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Color Scheme
color_scheme: TCM

# Navigation
aux_links:
  "Store":
    - "https://thecraftymachinist.com/"
aux_links_new_tab: true

# UI Features
back_to_top: true
back_to_top_text: "Back to top"
heading_anchors: true
nav_sort: case_insensitive
enable_copy_code_button: true

# -----------------------------------------------------------------------------
# Search Configuration
# -----------------------------------------------------------------------------
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  ChoosingACuttingTool:
    output: true
    permalink: /:collection/:path/
    
  Materials:
    output: true
    permalink: /:collection/:path/
    
  MachiningOperations:
    output: true
    permalink: /:collection/:path/

# Collection Navigation Settings
just_the_docs:
  collections:
    ChoosingACuttingTool:
      name: Choosing A Cutting Tool
      nav_exclude: false
      nav_fold: false
      
    Materials:
      name: Materials
      nav_exclude: false
      nav_fold: false
      
    MachiningOperations:
      name: Machining Operations
      nav_exclude: false
      nav_fold: false

# -----------------------------------------------------------------------------
# Default Front Matter
# -----------------------------------------------------------------------------
defaults:
  # All pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      nav_exclude: false
      search_exclude: false
  
  # Collection defaults    
  - scope:
      path: ""
      type: "ChoosingACuttingTool"
    values:
      layout: "default"
      parent: "Choosing A Cutting Tool"
      
  - scope:
      path: ""
      type: "Materials"
    values:
      layout: "default"
      parent: "Materials"
      
  - scope:
      path: ""
      type: "MachiningOperations"
    values:
      layout: "default"
      parent: "Machining Operations"

# -----------------------------------------------------------------------------
# Plugins (GitHub Pages compatible only)
# -----------------------------------------------------------------------------
plugins:
  - jekyll-seo-tag

# -----------------------------------------------------------------------------
# Markdown Processing
# -----------------------------------------------------------------------------
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# -----------------------------------------------------------------------------
# SASS Configuration
# -----------------------------------------------------------------------------
sass:
  style: compressed                    # Compressed for production
  sass_dir: _sass

# -----------------------------------------------------------------------------
# Callouts Configuration
# -----------------------------------------------------------------------------
callouts_level: quiet                  # or loud
callouts:
  # Safety and Educational Callouts
  warning:
    title: Warning
    color: red
    
  safety:
    title: Safety First
    color: red
    
  note:
    title: Note
    color: blue-000
    
  tip:
    title: Pro Tip
    color: green
    
  important:
    title: Important
    color: yellow
    
  # Educational Callouts
  try-this:
    title: Try This
    color: purple
    
  did-you-know:
    title: Did You Know?
    color: blue
    
  career-connection:
    title: Career Connection
    color: grey-dk
    
  # Material ISO Classifications
  material-iso-p:
    title: "ISO P - Steel"
    color: blue
    
  material-iso-m:
    title: "ISO M - Stainless Steel"
    color: yellow
    
  material-iso-k:
    title: "ISO K - Cast Iron"
    color: red
    
  material-iso-n:
    title: "ISO N - Non-Ferrous"
    color: green
    
  material-iso-s:
    title: "ISO S - Heat Resistant"
    color: purple
    
  material-iso-h:
    title: "ISO H - Hardened Steel"
    color: grey-dk
    
  material-iso-other:
    title: "Non-ISO Materials"
    color: grey-dk

# =============================================================================
# End of Configuration
# =============================================================================